# Generated by Django 5.2 on 2025-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_user', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('reporting_date', models.DateField()),
                ('category', models.CharField(choices=[('Drug Abuse and Trafficking', 'Drug Abuse and Trafficking'), ('Sexual Assault', 'Sexual Assault'), ('Cyber crime', 'Cyber crime'), ('Kidnapping', 'Kidnapping'), ('domestic violence', 'domestic violence')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=30)),
                ('police_officer', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Crimes',
                'verbose_name_plural': 'Crimes',
                'ordering': ['id'],
            },
        ),
    ]
