# Generated by Django 5.2 on 2025-05-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_remove_crimes_police_officer_crimes_active_status_and_more'),
        ('police_officers', '0002_alter_policeofficers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimes',
            name='police_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_officers.policeofficers'),
        ),
    ]
