# Generated by Django 5.2 on 2025-05-16 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0003_crimes_police_officer'),
        ('police_officers', '0005_alter_policeofficers_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='police_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_officers.policeofficers'),
        ),
        migrations.AlterField(
            model_name='crimes',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
