# Generated by Django 5.2 on 2025-05-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0004_alter_crimes_police_officer_alter_crimes_uuid'),
        ('police_officers', '0005_alter_policeofficers_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='police_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='police_officers.policeofficers'),
        ),
    ]
