# Generated by Django 5.2 on 2025-05-19 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0005_alter_crimes_police_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
