# Generated by Django 5.2 on 2025-05-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0006_alter_crimes_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimes',
            name='police_officer',
        ),
    ]
