# Generated by Django 5.2 on 2025-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Officers', 'Officers'), ('Users', 'Users')], max_length=15),
        ),
    ]
