# Generated by Django 5.2 on 2025-05-14 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='police_officer-image/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Police_officers',
                'verbose_name_plural': 'Police_officers',
            },
        ),
    ]
