# Generated by Django 5.2 on 2025-05-16 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policeofficers',
            options={'verbose_name': 'Police officers', 'verbose_name_plural': 'Police officers'},
        ),
        migrations.AlterField(
            model_name='policeofficers',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False),
        ),
    ]
