# Generated by Django 5.2 on 2025-05-16 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_officers', '0002_alter_policeofficers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficers',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
