# Generated by Django 5.2 on 2025-05-16 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_officers', '0004_alter_policeofficers_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficers',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
