# Generated by Django 5.2 on 2025-05-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0007_remove_crimes_police_officer'),
        ('police_officers', '0005_alter_policeofficers_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliceOfficers',
        ),
    ]
